# v0.3.0
# { "Depends": "py-genlayer:5jycge4q8k23462jtb0b9fyey1s9qz928sz2nbrd9mg4sxqg2qng" }

# ListingGate - a minimal consumer of PassportMap, proving a passport map
# can gate real actions on-chain: an asset can only be listed on a venue for
# users in a member state while PassportMap shows the venue authorised under
# MiCA for its services in THAT state - on a fresh check of a recent
# register - and a settlement is only recorded if the venue is covered AT
# THE TIME OF SETTLEMENT. A listing is a record, never a standing
# permission: if the venue's authorisation is withdrawn, or the register it
# was read from goes stale, listed assets can't settle until PassportMap
# covers the venue again.
#
# Studio Next port of contracts/listing_gate.py (the locally-tested,
# GenVM v0.2.11 source of truth), generated by scripts/port_to_studio_next.py.
# Only GenVM import / decorator / base-class / message spellings differ.
# Validated live on Studio Next (genlayer-test's Direct Mode does not
# support this generation) - see CONTRACT.md.
# Header must end in a blank line (real GenVM requirement).

import genlayer as gl
from genlayer.types import *
from genlayer.storage import TreeMap, DynArray
from dataclasses import dataclass
import datetime
import re

MAX_PAGE_LIMIT = 50
# EU-27 + the three EEA EFTA states, as PassportMap's map covers them. Done
# here as well so every check that needs no cross-contract call runs first.
STATES = (
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE",
    "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE",
    "IS", "LI", "NO",
)


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise gl.vm.UserError(message)


def _now() -> datetime.datetime:
    return datetime.datetime.fromisoformat(gl.message.datetime)


def _state(raw: str) -> str:
    code = raw.strip().upper()
    code = "GR" if code == "EL" else code  # ESMA's files write Greece as EL
    _require(code in STATES, "state must be an EU/EEA country code, e.g. DE")
    return code


def _asset(raw: str) -> str:
    asset = raw.strip().upper()
    _require(re.fullmatch(r"[A-Z0-9]{1,12}", asset) is not None, "asset must be 1-12 letters or digits")
    return asset


def _key(firm_id: str, asset: str, state: str) -> str:
    return f"{firm_id}|{asset}|{state}"


@gl.storage.allow
@dataclass
class Listing:
    firm_id: str
    asset: str
    state: str
    snapshot_id: u32  # the PassportMap snapshot that covered it
    register_as_of: str  # that snapshot's register date
    listed_at: datetime.datetime


@gl.storage.allow
@dataclass
class Settlement:
    key: str
    amount: u256
    snapshot_id: u32  # the snapshot in force when it settled
    recorded_at: datetime.datetime


class ListingGate(gl.contract.Contract):
    owner: Address
    passport_address: Address
    max_age_seconds: u32
    max_register_age_days: u32
    listings: DynArray[Listing]
    listed: TreeMap[str, u32]  # key -> listing id + 1
    settlements: DynArray[Settlement]
    settled: TreeMap[str, u256]

    def __init__(self, passport_address: str, max_age_seconds: u32, max_register_age_days: u32) -> None:
        _require(max_age_seconds > 0, "max_age_seconds must be positive")
        _require(max_register_age_days > 0, "max_register_age_days must be positive")
        self.owner = gl.message.sender_address
        self.passport_address = Address(passport_address)
        self.max_age_seconds = max_age_seconds
        self.max_register_age_days = max_register_age_days

    # Lists an asset on a venue for one state - only while PassportMap covers
    # the venue there.
    @gl.public.write
    def list_asset(self, firm_id: str, asset: str, state: str) -> None:
        _require(gl.message.sender_address == self.owner, "only the owner can list assets")
        a, s = _asset(asset), _state(state)
        _require(_key(firm_id, a, s) not in self.listed, "already listed")
        coverage = self._coverage(firm_id, s)
        _require(coverage["covered"], f"listing {a} via {firm_id} in {s} refused: PassportMap says {coverage['reason']}")

        listing = self.listings.append_new_get()
        listing.firm_id = firm_id
        listing.asset = a
        listing.state = s
        listing.snapshot_id = u32(coverage["snapshot_id"])
        listing.register_as_of = coverage["register_as_of"]
        listing.listed_at = _now()
        self.listed[_key(firm_id, a, s)] = u32(len(self.listings))

    # Settles a trade of a listed asset - only if the venue is covered right
    # now, not merely when the asset was listed.
    @gl.public.write
    def settle(self, firm_id: str, asset: str, state: str, amount: u256) -> None:
        _require(gl.message.sender_address == self.owner, "only the owner can settle")
        a, s = _asset(asset), _state(state)
        _require(amount > 0, "amount must be positive")
        key = _key(firm_id, a, s)
        _require(key in self.listed, "asset not listed")
        coverage = self._coverage(firm_id, s)
        _require(coverage["covered"], f"settlement of {a} via {firm_id} in {s} blocked: PassportMap says {coverage['reason']}")

        record = self.settlements.append_new_get()
        record.key = key
        record.amount = amount
        record.snapshot_id = u32(coverage["snapshot_id"])
        record.recorded_at = _now()
        self.settled[key] = u256(self.settled.get(key, u256(0)) + amount)

    def _coverage(self, firm_id: str, state: str) -> dict:
        passport = gl.contract.get_at(self.passport_address)
        return passport.view().get_coverage(firm_id, state, self.max_age_seconds, self.max_register_age_days)

    @gl.public.view
    def get_listing(self, firm_id: str, asset: str, state: str) -> dict:
        key = _key(firm_id, _asset(asset), _state(state))
        _require(key in self.listed, "asset not listed")
        listing = self.listings[self.listed[key] - 1]
        return {"firm_id": listing.firm_id, "asset": listing.asset, "state": listing.state,
                "snapshot_id": listing.snapshot_id, "register_as_of": listing.register_as_of,
                "listed_at": listing.listed_at.isoformat(), "settled": self.settled.get(key, u256(0))}

    @gl.public.view
    def get_listings(self, offset: u32, limit: u32) -> list:
        limit = min(limit, MAX_PAGE_LIMIT)
        out = []
        i = len(self.listings) - 1 - offset
        while i >= 0 and len(out) < limit:
            l = self.listings[i]
            out.append({"firm_id": l.firm_id, "asset": l.asset, "state": l.state, "snapshot_id": l.snapshot_id,
                        "register_as_of": l.register_as_of, "listed_at": l.listed_at.isoformat(),
                        "settled": self.settled.get(_key(l.firm_id, l.asset, l.state), u256(0))})
            i -= 1
        return out

    @gl.public.view
    def get_settlements(self, offset: u32, limit: u32) -> list:
        limit = min(limit, MAX_PAGE_LIMIT)
        out = []
        i = len(self.settlements) - 1 - offset
        while i >= 0 and len(out) < limit:
            r = self.settlements[i]
            out.append({"key": r.key, "amount": r.amount, "snapshot_id": r.snapshot_id,
                        "recorded_at": r.recorded_at.isoformat()})
            i -= 1
        return out

    @gl.public.view
    def get_config(self) -> dict:
        return {"owner": self.owner.as_hex, "passport_address": self.passport_address.as_hex,
                "max_age_seconds": self.max_age_seconds, "max_register_age_days": self.max_register_age_days,
                "listing_count": len(self.listings), "settlement_count": len(self.settlements)}
